name: Build and Deploy Joomla Extension

on:
  push:
    branches:
      - HEAD
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        uses: hmarr/debug-action@v3.0.0

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install zip
        run: sudo apt-get install zip -y

      - name: List Files in Current Directory (for debugging)
        run: ls -la

      - name: Create zip file
        run: |
          mkdir -p dist
          zip -r dist/semantyca-extension.zip com_semantycanm

      - name: Install extension on Joomla server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          PORT: ${{ secrets.SERVER_PORT }}
          JOOMLA_PATH: ${{ secrets.JOOMLA_PATH }}
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          scp -P $PORT dist/semantyca-extension.zip $SERVER_USER@$SERVER_HOST:/tmp/semantyca-extension.zip
          ssh -p $PORT $SERVER_USER@$SERVER_HOST "php $JOOMLA_PATH/cli/joomla.php extension:install /tmp/semantyca-extension.zip"
