name: Build and Deploy Joomla Extension

on:
  push:
    branches:
      - main 
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # ... (Checkout and Install Dependencies steps remain the same) ...

      - name: Create Zip File
        run: |
          mkdir -p dist
          zip -r dist/semantyca-extension.zip com_semantycanm

      - name: Prepare SSH Key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
     
      - name: Add Host Key (if needed)
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
        run: ssh-keyscan -H $SERVER_HOST >> ~/.ssh/known_hosts

      - name: Copy Extension to Server
        env:
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_PORT: ${{ secrets.SERVER_PORT }}  
        run: scp -o StrictHostKeyChecking=no -P $SERVER_PORT dist/semantyca-extension.zip $SERVER_USER@$SERVER_HOST:/tmp/

      - name: Install Extension
        env:
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_PORT: ${{ secrets.SERVER_PORT }}  
          JOOMLA_PATH: ${{ secrets.JOOMLA_PATH }}
        run: |
          ssh -p $SERVER_PORT $SERVER_USER@$SERVER_HOST "php $JOOMLA_PATH/cli/joomla.php extension:install /tmp/semantyca-extension.zip"

      # Optionally, remove the temporary zip file
      - name: Clean Up Temporary Files on Server (Optional)
        env:
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_PORT: ${{ secrets.SERVER_PORT }}  
        run: |
          ssh -p $SERVER_PORT $SERVER_USER@$SERVER_HOST "rm /tmp/semantyca-extension.zip"
